[biomes]
enabled = true
textFadeInTime = 10
textDisplayTime = 50
textFadeOutTime = 10
textCooldownTime = 200
textColor = "ffffff"
textSize = 1.5
renderShadow = true
textYOffset = -70
textXOffset = 0
biomeBlacklist = "[minecraft:the_end, minecraft:river, minecraft:frozen_river]"
recentBiomeCacheSize = 5
centerText = true
resetBiomeCacheOnDimensionChange = false
onlyUpdateAtSurface = true
[dimensions]
enabled = true
textFadeInTime = 10
textDisplayTime = 70
textFadeOutTime = 20
textColor = "ffffff"
textSize = 2.0
renderShadow = true
textYOffset = -75
textXOffset = 0
dimensionBlacklist = "[]"
centerText = true
onlyUpdateAtSurface = false
[sound]
biomeVolume = 1.0
biomePitch = 1.0
dimensionVolume = 1.0
dimensionPitch = 1.0
